### PR TITLE
distance: Add PhPointF to DistanceEuclidean

### PR DESCRIPTION
**Pull request by ctbur**
## Changes
Add a function to calculate the L2 distance between two `PhPointF`s to DistanceEuclidean.

## Verification
It's already used in tests.

### CODE REVIEW

**Comment by improbable-til** [comment]
This looks like a sensible change, however it means breaking the API. 
I won't merge it now but we could leave it open until a next major release?

**Comment by ctbur** [comment]
I don't see how it would break the API since the only adds a function and modifies some code for testing. Is it because of something with C++ templates that I am not aware of? Either way it's not urgent, it can wait until the next major release.

**Comment by improbable-til** [comment]
It would break the API because it removes `DistanceEuclideanFloat`.
Removing it would may break any code that uses it, such as `begin_query_knn` for `float`, same as the unit test you had to adapt.

**Comment by ctbur** [comment]
Ah, but `DistanceEuclideanFloat` is only declared within `phtree_f_test.cc`, so it should not be usable outside that compilation unit. Aside from modifying the test file the PR only adds one function in `distance.h`.

**Comment by improbable-til** [comment]
Sorry for the delay.
You are right, I thought it is all in `distance.h`.

**Pull request merged**
